// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmGxTGFvpqLX2YxlgR0GO2TPkZ7mpsEzI',
    appId: '1:548760440945:web:f277b6b7f3c64ebcd80bd0',
    messagingSenderId: '548760440945',
    projectId: 'study-hub-b81c1',
    authDomain: 'study-hub-b81c1.firebaseapp.com',
    storageBucket: 'study-hub-b81c1.appspot.com',
    measurementId: 'G-3FNEWK00LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bURAUkaphXsAtcwkBfyoW5M6VW_5moY',
    appId: '1:548760440945:android:3847a7190c9332d7d80bd0',
    messagingSenderId: '548760440945',
    projectId: 'study-hub-b81c1',
    storageBucket: 'study-hub-b81c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ecs7--Btw9sb8-DzY0f84YGeoVBXokc',
    appId: '1:548760440945:ios:d984236506f6fefad80bd0',
    messagingSenderId: '548760440945',
    projectId: 'study-hub-b81c1',
    storageBucket: 'study-hub-b81c1.appspot.com',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ecs7--Btw9sb8-DzY0f84YGeoVBXokc',
    appId: '1:548760440945:ios:4b9b0ad40393c4ebd80bd0',
    messagingSenderId: '548760440945',
    projectId: 'study-hub-b81c1',
    storageBucket: 'study-hub-b81c1.appspot.com',
    iosBundleId: 'com.example.studyhub.RunnerTests',
  );
}
