/// 画面ID
enum PageId {
  login,
  loginByGoogle,
  authPage,
  resetPassword,
  profileInput,
  menu,
  searchTeachers,
  favoriteTeachers,
  notifications,
  editProfile,
  myPage,
  evaluationPage,
  selectTeachers,
  addQuestion,
  teacherProfile,
  home,
  questionAndAnswerPage,
  searchQuestions,
  reportQuestionPage,
  checkQuestionImagePage,
  checkAnswerImagePage,
  notificationDetailPage,
  page1,
  page2,
  page3,
}

/// 画面パス
extension PagePath on PageId {
  String get path => switch (this) {
        PageId.login => "/login",
        PageId.loginByGoogle => "/loginByGoogle",
        PageId.authPage => "/authPage",
        PageId.resetPassword => "/resetPassword",
        PageId.profileInput => "/profileInput",
        PageId.menu => "/menu",
        PageId.searchTeachers => "/searchTeachers",
        PageId.favoriteTeachers => "/favoriteTeachers",
        PageId.notifications => "/notifications",
        PageId.editProfile => "/editProfile",
        PageId.myPage => "/myPage",
        PageId.evaluationPage => "/evaluationPage",
        PageId.selectTeachers => "/selectTeachers",
        PageId.addQuestion => "/addQuestion",
        PageId.teacherProfile => "/teacherProfile",
        PageId.home => "/home",
        PageId.questionAndAnswerPage => "/questionAndAnswerPage",
        PageId.searchQuestions => "/searchQuestions",
        PageId.reportQuestionPage => "/reportQuestionPage",
        PageId.checkQuestionImagePage => "/checkQuestionImagePage",
        PageId.checkAnswerImagePage => "/checkAnswerImagePage",
        PageId.notificationDetailPage => "/notificationDetailPage",
        PageId.page1 => "/page1",
        PageId.page2 => "/page2",
        PageId.page3 => "/page3",
      };
}

/// 画面名
extension PageName on PageId {
  String get routeName => switch (this) {
        PageId.login => "login",
        PageId.loginByGoogle => "/loginByGoogle",
        PageId.authPage => "authPage",
        PageId.resetPassword => "resetPassword",
        PageId.profileInput => "/profileInput",
        PageId.menu => "/menu",
        PageId.searchTeachers => "/searchTeachers",
        PageId.favoriteTeachers => "/favoriteTeachers",
        PageId.notifications => "/notifications",
        PageId.editProfile => "/editProfile",
        PageId.myPage => "/myPage",
        PageId.evaluationPage => "/evaluationPage",
        PageId.selectTeachers => "/selectTeachers",
        PageId.addQuestion => "/addQuestion",
        PageId.teacherProfile => "/teacherProfile",
        PageId.home => "/home",
        PageId.questionAndAnswerPage => "/questionAndAnswerPage",
        PageId.searchQuestions => "/searchQuestions",
        PageId.reportQuestionPage => "/reportQuestionPage",
        PageId.checkQuestionImagePage => "/checkQuestionImagePage",
        PageId.checkAnswerImagePage => "/checkAnswerImagePage",
        PageId.notificationDetailPage => "/notificationDetailPage",
        PageId.page1 => "page1",
        PageId.page2 => "page2",
        PageId.page3 => "page3",
      };
}
